import type { Metadata } from 'next';
import { Exo, Outfit } from 'next/font/google';
import clsx from 'clsx';
import { getClientConfig } from '@/lib/config';
import { ConfigProvider } from '@/lib/providers/ConfigProvider';
import './globals.css';

const outfit = Outfit({
	variable: '--font-outfit',
	weight: ['400', '500', '600', '700', '800'],
	subsets: ['latin']
});

const exo = Exo({
	variable: '--font-exo',
	weight: ['400', '500', '600', '700', '800'],
	subsets: ['latin']
});

export const metadata: Metadata = {
	title: 'Williamstown SC',
	description: 'Generated by create next app',
	manifest: '/favicon/site.webmanifest'
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	const config = getClientConfig();

	return (
		<html lang="en">
			<body className={clsx(outfit.variable, exo.variable, 'antialiased')}>
				<ConfigProvider config={config}>{children}</ConfigProvider>
			</body>
		</html>
	);
}
