import type { Metadata } from 'next';
import { Exo, Outfit } from 'next/font/google';
import clsx from 'clsx';
import { GoogleTagManager, PageViewTracker } from '@/components/analytics';
import { getClientConfig, isLocal } from '@/lib/config';
import { getSiteSettings } from '@/lib/content';
import { ConfigProvider } from '@/lib/providers/ConfigProvider';
import './globals.css';

const outfit = Outfit({
	variable: '--font-outfit',
	weight: ['400', '500', '600', '700', '800'],
	subsets: ['latin']
});

const exo = Exo({
	variable: '--font-exo',
	weight: ['400', '500', '600', '700', '800'],
	subsets: ['latin']
});

export const metadata: Metadata = {
	title: 'Williamstown SC',
	description: 'Generated by create next app',
	manifest: '/favicon/site.webmanifest'
};

export default async function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	const config = getClientConfig();
	const siteSettings = await getSiteSettings();

	// Only load GTM in production with valid GTM ID
	const gtmId = siteSettings?.analytics?.gtmId;
	const shouldLoadGtm = !isLocal() && !!gtmId;

	return (
		<html lang="en">
			{shouldLoadGtm && gtmId && <GoogleTagManager gtmId={gtmId} />}
			<body className={clsx(outfit.variable, exo.variable, 'antialiased')}>
				<ConfigProvider config={config}>{children}</ConfigProvider>
				{shouldLoadGtm && <PageViewTracker />}
			</body>
		</html>
	);
}
